version: '3.7'
services:
  postgres:
    image: library/postgres:13.1
    healthcheck:
      test: psql postgres --command "select 1"
    stop_grace_period: 120s
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: seed_data
    volumes:
      - /var/lib/postgresql/data
    networks:
      - core-config-server_app_net

  distributed-environment-server:
    image: distributed-environment-server:0.0.1-SNAPSHOT
    ports:
      - 8888:8888
    networks:
      - core-config-server_app_net

  eureka-server:
    image: eureka-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    depends_on:
      - distributed-environment-server
    networks:
      - core-config-server_app_net

networks:
  app_net:
    driver: bridge
  core-config-server_app_net:
    external: true