version: '3.7'
services:
  postgres:
    image: library/postgres:13.1
    healthcheck:
      test: psql postgres --command "select 1"
    stop_grace_period: 120s
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: seed_data
    volumes:
      - /var/lib/postgresql/data
    networks:
      - core-config-server_app_net

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - core-config-server_app_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elastic
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /var/lib/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - core-config-server_app_net

  # elasticsearch browser
  dejavu:
    image: appbaseio/dejavu:3.0.0-alpha
    container_name: dejavu
    ports:
      - "1358:1358"
    networks:
      - core-config-server_app_net

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
    networks:
      - core-config-server_app_net

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - core-config-server_app_net

  #logstash:
    #  image: docker.elastic.co/logstash/logstash:7.5.0
    # container_name: logstash
      #environment:
      #- "ELASTIC_PASSWORD=password"
    #ports: [ '9600:9600' ]
    #depends_on: [ 'elasticsearch' ]
      #volumes:
      # - /var/lib/logstash/data
      #- /var/lib/log/data
      #networks:
      #- core-config-server_app_net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: kibana
    environment:
      - "ELASTIC_PASSWORD=password"
    ports: [ '5601:5601' ]
    networks:
      - core-config-server_app_net

networks:
  app_net:
    driver: bridge
  core-config-server_app_net:
    external: true