version: '3.7'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - core-config-server_app_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elastic
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - /var/lib/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - core-config-server_app_net

  # elasticsearch browser
  dejavu:
    image: appbaseio/dejavu:3.0.0-alpha
    container_name: dejavu
    ports:
      - "1358:1358"
    networks:
      - core-config-server_app_net

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    hostname: zookeeper
    networks:
      - core-config-server_app_net

  kafka:
    image: wurstmeister/kafka
    command: [ start-kafka.sh ]
    ports:
      - "9092"
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/lib/kafka/data
    depends_on:
      - "zookeeper"
    networks:
      - core-config-server_app_net

  logstash:
    image: docker.elastic.co/logstash/logstash:7.5.0
    container_name: logstash
    environment:
      - "ELASTIC_PASSWORD=idrica"
    ports: [ '9600:9600' ]
    depends_on: [ 'elasticsearch' ]
    volumes:
      - /var/lib/logstash/data
      - /var/lib/log/data
    networks:
      - core-config-server_app_net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: kibana
    environment:
      - "ELASTIC_PASSWORD=idrica"
    ports: [ '5601:5601' ]
    networks:
      - core-config-server_app_net

networks:
  app_net:
    driver: bridge
  core-config-server_app_net:
    external: true