version: '3.7'
services:
  postgres:
    image: library/postgres:13.1
    healthcheck:
      test: psql postgres --command "select 1"
    stop_grace_period: 120s
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: seed_data
    volumes:
      - /var/lib/postgresql/data
    networks:
      - core-config-server_app_net

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - core-config-server_app_net

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elastic
    environment:
      - node.name=elastic
      - cluster.name=es-docker-cluster
      #- discovery.seed_hosts=es02,es03
      #- cluster.initial_master_nodes=es01,es02,es03
      - cluster.initial_master_nodes=elastic
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /var/lib/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - core-config-server_app_net

  # elasticsearch browser
  dejavu:
    image: appbaseio/dejavu:3.0.0-alpha
    container_name: dejavu
    ports:
      - "1358:1358"
    networks:
      - core-config-server_app_net

networks:
  app_net:
    driver: bridge
  core-config-server_app_net:
    external: true